# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IdeaVateNews' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IdeaVateNews

  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'IQKeyboardManagerSwift'
  pod 'SVProgressHUD'
  pod 'ReachabilitySwift'
  pod 'Kingfisher'
  
end
